// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaghSyR8_TISxbwN1T2HVt_waYOO0A9II',
    appId: '1:710615234824:web:8775e718f54818309ed4bd',
    messagingSenderId: '710615234824',
    projectId: 'plateformeservices-72c64',
    authDomain: 'plateformeservices-72c64.firebaseapp.com',
    storageBucket: 'plateformeservices-72c64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-mDJGcq2e0Rb9C6tvYxSj4KwNnY59FM',
    appId: '1:710615234824:android:549a2216de7fcadc9ed4bd',
    messagingSenderId: '710615234824',
    projectId: 'plateformeservices-72c64',
    storageBucket: 'plateformeservices-72c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYihQJW-kAOdGtPKXIoPn7D-RZD51V6ak',
    appId: '1:710615234824:ios:97af65a32fc44e889ed4bd',
    messagingSenderId: '710615234824',
    projectId: 'plateformeservices-72c64',
    storageBucket: 'plateformeservices-72c64.firebasestorage.app',
    iosClientId: '710615234824-1cqqktf9bjgih373bqg13esdjl44o33v.apps.googleusercontent.com',
    iosBundleId: 'com.example.plateformeServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaghSyR8_TISxbwN1T2HVt_waYOO0A9II',
    appId: '1:710615234824:web:8e4bdedface6a35b9ed4bd',
    messagingSenderId: '710615234824',
    projectId: 'plateformeservices-72c64',
    authDomain: 'plateformeservices-72c64.firebaseapp.com',
    storageBucket: 'plateformeservices-72c64.firebasestorage.app',
  );
}
